# Generated by Django 5.2.7 on 2025-12-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_review_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
    ]
