# Generated by Django 5.2.7 on 2025-12-15 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_genre_alter_game_genre_game_genret'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='genre',
        ),
    ]
