# Generated by Django 5.2.7 on 2025-12-15 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_game_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='genreT',
            new_name='genre',
        ),
    ]
